spring:
  datasource:
    url: jdbc:mysql://116.62.25.111/yanglaoyuan?useUnicode=true&characterEncoding=UTF-8
    username: yanglaoyuan
    password: yanglaoyuan123.
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    fliter: stat
  thymeleaf:
    cache: false
    prefix: classpath:/view/
server:
  port: 8089
mybatis:
  type-aliases-package: com.yanglaoyuan.pojo
  mapper-locations: classpath:Mapper/*Mapper.xml
jackson:
  date-format: yyyy-MM-dd
  time-zone: GMT+8
